spring.datasource.url=jdbc:mysql://localhost:3306/ADHD_HobbyCollector
spring.datasource.username=root
spring.datasource.password=YOUR_MYSQL_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never